# Generated by Django 5.0.7 on 2024-09-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='hello.jpg', upload_to='product_img'),
        ),
    ]
